# DocumentOut, DocumentUpdate
from datetime import datetime
from typing import Annotated
from pydantic import BaseModel, Field, PositiveInt, ConfigDict


class DocumentCreate(BaseModel):
    """Pydantic model for creating a new document, for POST requests"""
    name: Annotated[str, Field(min_length=4, max_length=100)]

    # automated parts
    # url: Annotated[str, Field(max_length=200)]  # after s3 upload
    project_id: PositiveInt

    # owner_id: PositiveInt     # assigned automatically from the current user, ntot input from the user
    # id: PositiveInt

    # When validating this model, accept objects with attributes (e.g. obj.id) as input
    model_config = ConfigDict(from_attributes=True)


class DocumentUpdate(BaseModel):
    """Pydantic model for updating an existing document, for PUT requests"""
    name: Annotated[str, Field(min_length=4, max_length=100)] | None = None

    # url: Annotated[str, Field(max_length=200)] | None = None  # s3, probably not needed, as it is generated by the system, not user input

    model_config = ConfigDict(from_attributes=True)


class DocumentOut(BaseModel):  #
    """Pydantic model for returning document data, for GET requests"""
    id: PositiveInt
    owner_id: PositiveInt
    name: Annotated[str, Field(max_length=100)]
    project_id: PositiveInt
    url: Annotated[str, Field(max_length=500)]  # s3
    created_at: datetime
    updated_at: datetime | None = None

    # When validating this model, accept objects with attributes (e.g. obj.id) as input
    model_config = ConfigDict(from_attributes=True)
