# UserCreate/Update, UserOut
from pydantic import BaseModel, Field, PositiveInt
from typing import Annotated


class User(BaseModel):
    id: int  # Use simple integer for id, as it will be auto-generated by the database ?
    login: Annotated[str, Field(max_length=100)]
    # Only in Create/Update
    password: Annotated[str, Field(min_length=8, max_length=100)]
    projects: Annotated[list, Field(default_factory=list)]

    class Config:
        from_attributes = True


class UserOut(BaseModel):
    id: int
    login: str

    class Config:
        from_attributes = True
